services:
  download-tool:
    container_name: download-tool
    build:
      context: .
      dockerfile: ./Docker/downloadTool/Dockerfile
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer
    volumes:
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/wslg
      - ./tciadownload:/root/Desktop
      - ./tcia:/tcia
      - ./config:/config
    network_mode: host